// Generated by Dagger (https://dagger.dev).
package com.sabgil.bbuckkugi.data.repository;

import android.content.Context;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ConnectionManagerImpl_Factory implements Factory<ConnectionManagerImpl> {
  private final Provider<Context> contextProvider;

  public ConnectionManagerImpl_Factory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public ConnectionManagerImpl get() {
    return newInstance(contextProvider.get());
  }

  public static ConnectionManagerImpl_Factory create(Provider<Context> contextProvider) {
    return new ConnectionManagerImpl_Factory(contextProvider);
  }

  public static ConnectionManagerImpl newInstance(Context context) {
    return new ConnectionManagerImpl(context);
  }
}
