// Generated by Dagger (https://dagger.dev).
package com.sabgil.bbuckkugi.data.repository;

import android.app.Activity;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class KakaoLoginRepositoryImpl_Factory implements Factory<KakaoLoginRepositoryImpl> {
  private final Provider<Activity> activityProvider;

  public KakaoLoginRepositoryImpl_Factory(Provider<Activity> activityProvider) {
    this.activityProvider = activityProvider;
  }

  @Override
  public KakaoLoginRepositoryImpl get() {
    return newInstance(activityProvider.get());
  }

  public static KakaoLoginRepositoryImpl_Factory create(Provider<Activity> activityProvider) {
    return new KakaoLoginRepositoryImpl_Factory(activityProvider);
  }

  public static KakaoLoginRepositoryImpl newInstance(Activity activity) {
    return new KakaoLoginRepositoryImpl(activity);
  }
}
